#!/usr/bin/env bash
# Translate HiveOS flight-sheet vars into miner.conf for alpha-miner.
#
# Flight sheet:
#   CUSTOM_TEMPLATE  → wallet[.worker]  (-u)
#   CUSTOM_URL       → pool host:port or stratum+tcp://...  (comma/space for failover)
#   CUSTOM_PASS      → password (-p), default x
#   CUSTOM_USER_CONFIG → extra flags, e.g.  -b opencl -d 0,1

[[ -z $SCRIPT_PATH ]] && SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
[[ -z $MINER_DIR ]] && MINER_DIR=/hive/miners/custom
[[ -f $SCRIPT_PATH/h-manifest.conf ]] && source "$SCRIPT_PATH/h-manifest.conf"

conf_file="${CUSTOM_CONFIG_FILENAME:-$MINER_DIR/$CUSTOM_NAME/miner.conf}"

wallet="${CUSTOM_TEMPLATE:-}"
pass="${CUSTOM_PASS:-x}"

declare -a POOLS=()
while IFS= read -r p || [[ -n "$p" ]]; do
  p="${p//[$'\t\r ']/}"
  [[ -n "$p" ]] && POOLS+=("$p")
done < <(printf '%s' "${CUSTOM_URL:-}" | tr ',[:space:]' '\n')

if [[ ${#POOLS[@]} -eq 0 ]]; then
  echo "ERROR: no pool URL (CUSTOM_URL empty)" >&2
  return 1 2>/dev/null || exit 1
fi

if [[ -z "$wallet" ]]; then
  echo "ERROR: no wallet (CUSTOM_TEMPLATE empty)" >&2
  return 1 2>/dev/null || exit 1
fi

# Default backend opencl on Hive (GPU rigs); user can override in extra config.
declare -a EXTRA_ARGS=()
declare -a WRAPPER_CFG=()
has_backend=0
if [[ -n "${CUSTOM_USER_CONFIG:-}" ]]; then
  # shellcheck disable=SC2206
  for tok in $CUSTOM_USER_CONFIG; do
    if [[ "$tok" =~ ^(FAILOVER_[A-Z0-9_]+|REPORT_METRIC|HSTATS_RAW_LINES)=.+$ ]]; then
      WRAPPER_CFG+=("$tok")
    else
      EXTRA_ARGS+=("$tok")
      [[ "$tok" == "-b" || "$tok" == "--backend" ]] && has_backend=1
    fi
  done
fi

declare -a BASE_ARGS=( -u "$wallet" -p "$pass" )
if [[ $has_backend -eq 0 ]]; then
  BASE_ARGS+=( -b opencl -k "$SCRIPT_PATH/blake3_an.cl" )
fi
BASE_ARGS+=( "${EXTRA_ARGS[@]}" )

{
  printf '# generated by h-config.sh v%s — do not edit by hand\n' "${CUSTOM_VERSION:-0}"
  printf 'POOLS=('
  for p in "${POOLS[@]}"; do printf ' %q' "$p"; done
  printf ' )\n'
  printf 'ALPHA_BASE_ARGS=('
  for a in "${BASE_ARGS[@]}"; do printf ' %q' "$a"; done
  printf ' )\n'
  for kv in "${WRAPPER_CFG[@]}"; do
    printf '%s\n' "$kv"
  done
} >"$conf_file"

echo "Wrote $conf_file"
echo "  pools: ${POOLS[*]}"
echo "  args:  ${BASE_ARGS[*]}"
